debian/diff: add missing #include to connect.c
A misresolved merge conflict dropped #include "tcp.h" from connect.c
between 1.8.4.2-1 and 1.8.5~rc0-1, which results in these build warnings:

    CC connect.o
connect.c: In function 'git_connect':
connect.c:379:3: warning: implicit declaration of function 'git_use_proxy' [-Wimplicit-function-declaration]
connect.c:380:4: warning: implicit declaration of function 'git_proxy_connect' [-Wimplicit-function-declaration]
connect.c:380:9: warning: assignment makes pointer from integer without a cast [enabled by default]
connect.c:382:4: warning: implicit declaration of function 'git_tcp_connect' [-Wimplicit-function-declaration]

Obviously this was a silly accident, but it will cause runtime crashes on
some architectures (https://wiki.debian.org/ImplicitPointerConversions),
as well as rejection on at least the Ubuntu amd64 buildds via a build log
filter.

Fixes: http://bugs.debian.org/728508
Signed-off-by: Jonathan Nieder <jrnieder@gmail.com>