git-p4: handle empty files for large file system
GitLFS creates no pointer file for empty files... therefore we can't find an OID:
oid = re.search(r'^oid \w+:(\w+)', pointerFile, re.MULTILINE).group(1)
AttributeError: 'NoneType' object has no attribute 'group'