diffcore-pickaxe: respect --no-textconv
Since ef90ab66e8ea (pickaxe: use textconv for -S counting, 2012-10-28),
the textconv filter is unconditionally applied for "log -S", and
there is no way to turn it off, even with the --no-textconv option.

    $ echo '*.txt diff=wrong' > .gitattributes
    $ git -c diff.wrong.textconv='xxx' log --no-textconv -Sfoo
    error: cannot run xxx: No such file or directory
    fatal: unable to read files to diff

Reported-by: Matthieu Moy <Matthieu.Moy@grenoble-inp.fr>
Signed-off-by: Simon Ruderich <simon@ruderich.org>
Signed-off-by: Junio C Hamano <gitster@pobox.com>