MINGW: git-compat-util.h: use inttypes.h for printf macros
1. Don't try to be smarter than libc and simply use printf macros
from inttypes.h.

All MinGW flavors have inttypes.h, so just include it.

Pass -D__USE_MINGW_ANSI_STDIO=1 to select
GNU-compatible macro definitions on MinGW-W64 [1]
and avoid 'BUG: your vsnprintf is broken' from strbuf.c.

As a side-effect, Git no longer builds with MSVC < 2010 due to
its lack of stdint.h.

2. compat/bswap.h uses uint32_t, so we must #include <stdint.h>
or <inttypes.h> to avoid error on MinGW-W64:

  compat/bswap.h:12:1: error: unknown type name 'uint32_t'

[1] http://sourceforge.net/p/mingw-w64/wiki2/gnu%20printf/

Signed-off-by: Marat Radchenko <marat@slonopotamus.org>